spring:
  datasource:
    password: root123
    url: jdbc:mysql://localhost:3306/bookstall
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
